[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/live-trains"
  to = "/.netlify/functions/live-trains"
  status = 200
